### ISSUE TITLE
Marking a widget as dirty from a worker thread

### ISSUE THREAD

**Issue by SirVer** [rust-gnome/gtk#128]
I tried to replicate this SO: http://stackoverflow.com/a/17458873/200945

Basically, I do some work in the background in other threads and now the GUI needs redrawing. I'd like to wake up the main loop from another thread. Unfortunately, it seems that rust-gtk implementation is convinced that it is unsafe. It might be even right... I have no idea. This code:

```rust
    let b1 = Arc::new(Mutex::new(some_widget));
    let b2 = b1.clone();
    let commands = some_receiver_channel.
    let t = thread::scoped(move || {
        while let Ok(command) = commands.recv() {
                let b = b2.lock().unwrap();
                 b.queue_draw();
         }
    });

    gtk::main();
~~~

states `the trait `core::marker::Send` is not implemented for the type *mut gtk_sys::GtkWidget`. That is correct, it isn't. This logic seems to work in C though. How can I achieve my design safely?

**Comment by gkoz** [comment]
Thou shalt not interact with GTK from any threads but the main one.
The recently added [`multithreading_context` example](https://github.com/rust-gnome/examples/blob/pending/src/multithreading_context.rs) illustrates the use of `idle_add` from the worker thread, but it's not the optimal solution. The `cairo_thread` example just polls the channel in a timeout handler.
Some relevant discussion here: https://gitter.im/rust-gnome/gtk?at=55baf23943481e53375ff7d0

**Comment by SirVer** [comment]
Thank you, good sir. The multithreading_context example helped a ton. 

For posteriority and others: The secret sauce here is: `glib::idle_add` is apparently thread safe (wasn't clear to me) and a thread_local can be used to implicitly pass an argument to the idle_add closure. A bit ugly and convoluted, but workable solution.

**Comment by gkoz** [comment]
Note that there's a cost of [twice-boxing a closure](https://github.com/rust-gnome/glib/blob/master/src/source.rs#L64) paid each time you call `idle_add`. We could add a variant that would take `fn` instead.

Another pitfall is that presently `idle_add` doesn't require `F: Send` (I'm still not sure how to do that without destroying single-threaded ergonomics, like, what if you want to capture a widget) but some day it will.

**Comment by SirVer** [comment]
Well, if you require `F: Send`, the whole setup with the thread local will no longer work.... and a Mutex won't either since widgets are not send. tricky.

Thanks for all your help with this issue.

**Comment by gkoz** [comment]
In the example we use a `fn`, which I believe always is `Send`, in place of a closure.

**Comment by SirVer** [comment]
Ahh, makes sense.
