### ISSUE TITLE
 Support Windows 

### ISSUE THREAD

**Issue by GuillaumeGomez** [rust-gnome/gtk#17]
[original](https://github.com/jeremyletang/rgtk/issues/26).

**Comment by StephanvanSchaik** [comment]
It does build on Microsoft Windows, here are some of the current examples.

![](http://i.imgur.com/IZaHC0T.png)

![](http://i.imgur.com/zISowvi.png)

**Comment by GuillaumeGomez** [comment]
Oh nice ! It's good to close then ! :-)
