### ISSUE TITLE
Agreement to license change (from LGPL to MIT)

### ISSUE THREAD

**Issue by GuillaumeGomez** [rust-gnome/gtk#20]
For the moment, here are the contributors who agreed to the change of license:
 * [oakes](https://github.com/jeremyletang/rgtk/commit/ddcf5e37d6da809a45eed3de5c792e94edccc1bd#commitcomment-10536262)
 * [buster](https://github.com/jeremyletang/rgtk/commit/ddcf5e37d6da809a45eed3de5c792e94edccc1bd#commitcomment-10538745)
 * [gkoz](https://github.com/jeremyletang/rgtk/commit/ddcf5e37d6da809a45eed3de5c792e94edccc1bd#commitcomment-10540678)
 * [SimonSapin](https://github.com/jeremyletang/rgtk/commit/ddcf5e37d6da809a45eed3de5c792e94edccc1bd#commitcomment-10541862)
 * [bpbp-boop](https://github.com/rust-gnome/gtk/issues/20#issuecomment-88863537)
 * [dndanik](https://github.com/rust-gnome/gtk/issues/20#issuecomment-88870497)
 * [Blei](https://github.com/rust-gnome/gtk/issues/20#issuecomment-88878757)
 * [jgillich](https://github.com/rust-gnome/gtk/issues/20#issuecomment-88883661)
 * [osa1](https://github.com/jeremyletang/rgtk/commit/ddcf5e37d6da809a45eed3de5c792e94edccc1bd#commitcomment-10544903)
 * [frewsxcv](https://github.com/jeremyletang/rgtk/commit/ddcf5e37d6da809a45eed3de5c792e94edccc1bd#commitcomment-10552466)
 * [steveklabnik](https://github.com/jeremyletang/rgtk/commit/ddcf5e37d6da809a45eed3de5c792e94edccc1bd#commitcomment-10554082)
 * [gsingh93](https://github.com/jeremyletang/rgtk/commit/ddcf5e37d6da809a45eed3de5c792e94edccc1bd#commitcomment-10557420)
 * [gekola](https://github.com/jeremyletang/rgtk/commit/ddcf5e37d6da809a45eed3de5c792e94edccc1bd#commitcomment-10582070)
 * [TobiasBales](https://github.com/jeremyletang/rgtk/commit/ddcf5e37d6da809a45eed3de5c792e94edccc1bd#commitcomment-10597716)
 * [ptersilie](https://github.com/rust-gnome/gtk/issues/20#issuecomment-91191617)
 * [mathijshenquet](https://github.com/rust-gnome/gtk/issues/20#issuecomment-91276737)

**Comment by bpbp-boop** [comment]
I give permission for all my work on rgtk to be re-licensed under an MIT license.

**Comment by dndanik** [comment]
I give my permission.

**Comment by Blei** [comment]
I agree with re-licensing my contribution(s) under an MIT license.

**Comment by jgillich** [comment]
I agree with re-licensing my contribution(s) under an MIT license.

Just because I'm curious, what are the reasons for this change? GTK+ is LGPL licensed, I think you still have to conform to its terms even if the bindings are MIT. But IANAL.

**Comment by GuillaumeGomez** [comment]
@jgillich: Mostly for the reasons given [here](https://github.com/jeremyletang/rgtk/pull/248#issuecomment-86233795).

**Comment by gkoz** [comment]
> Just because I'm curious, what are the reasons for this change? GTK+ is LGPL licensed, I think you still have to conform to its terms even if the bindings are MIT.

We're only using the information from GTK's header files so this work isn't supposed to be infected by [L]GPL. We likely still are required to put the text of those licences into the repo and some notices.

**Comment by ptersilie** [comment]
MIT sounds good to me. Permission granted of course.

**Comment by GuillaumeGomez** [comment]
@ptersilie: thanks !

**Comment by gkoz** [comment]
It seems we're missing permission from @mathijshenquet

**Comment by mathijshenquet** [comment]
I agree to this change, and any other future changes the rgtk team would
like to make to the license.

Sorry for the late response

**Comment by gkoz** [comment]
Thank you, @mathijshenquet, this is a relief. :)

**Comment by GuillaumeGomez** [comment]
@mathijshenquet: it's been a while ! Hope you're doing fine. Thanks for your agreement !

**Comment by GuillaumeGomez** [comment]
Since everyone concerned by the change of license has given his agreement, we can close this issue. If I'm wrong, don't hesitate to notify me !

**Comment by JohnMHarrisJr** [comment]
"infected by GPL"

Right. Okay.
