### ISSUE TITLE
Set up Travis CI.

### ISSUE THREAD

**Issue by StephanvanSchaik** [rust-gnome/gtk#23]
The [original repository](https://github.com/jeremyletang/rgtk) had support for [Travis CI](https://travis-ci.org/). It would be nice if this, or an alternative, could be set up again.

**Comment by GuillaumeGomez** [comment]
I tried to but travis doesn't do it (don't know why). To be more precise, it does turn off travis for rust-gome repos and then turn it back off. I'm still looking for finding out what's wrong. @jeremyletang will take a look tomorrow.

**Comment by GuillaumeGomez** [comment]
It's finally done ! We can close =D

**Comment by gkoz** [comment]
Something along the lines of https://github.com/rust-gnome/gtk/pull/25#issuecomment-91927978 so we could notice inter-repo breakage might still be on the table.
