### ISSUE TITLE
Notebooks expect labels rather than widgets.

### ISSUE THREAD

**Issue by StephanvanSchaik** [rust-gnome/gtk#26]
The [documentation for GTK+ 3](https://developer.gnome.org/gtk3/stable/GtkNotebook.html) shows that most functions that currently expect a `Label`, should in fact be able to accept widgets of any type (i.e. use `Widget`).

I am working on a patch that fixes this. Although if there is anything I need to know while working on this, then that kind of information is welcome.

**Comment by gkoz** [comment]
It looks like we'll be taking random types of widgets a lot. It might be worth pondering whether [static](https://github.com/rust-gnome/gtk/blob/master/src/gtk/widgets/note_book.rs#L33) or dynamic dispatch is preferable here.

**Comment by gkoz** [comment]
The position arguments seem to call for a type that would let us specify either a specific number, or 'end'. `Option` could work for that but would be less explicit. Do any other parts of gtk use the same convention?

**Comment by StephanvanSchaik** [comment]
At the moment, I would propose the following [patch](http://www.synkhronix.com/pub/rust/patches/rgtk/0001-notebook-changed-functions-to-accept-widgets-rather-.patch) to fix the issue with the widget types (I'll send a pull request later).

Well, there are similar cases of `insert` functions, such as [this one](https://developer.gnome.org/gtk3/stable/GtkToolbar.html#gtk-toolbar-insert).

**Comment by gkoz** [comment]
The input position parameters will need a separate PR then to decide on the type to use.
I'll make a PR to add a conversion for `Option<u32>` so we can at least give the output values the `time_t` treatment.
You can avoid a little bit of `gtk::` repetitiveness by importing the `WidgetTrait`.

**Comment by gkoz** [comment]
https://github.com/rust-gnome/glib/pull/5 should help reduce boilerplate in cases where negative values represents failure.

**Comment by GuillaumeGomez** [comment]
With the PR merged, I guess this issue can be closed ?

**Comment by StephanvanSchaik** [comment]
Yes, this issue has been resolved :).
