### ISSUE TITLE
no matching package named `gdk3-sys`

### ISSUE THREAD

**Issue by oakes** [rust-gnome/gtk#27]
Error when attempting to build after the latest Cargo.toml changes:

```
no matching package named `gdk3-sys` found (required by `rgtk`)
location searched: https://github.com/rust-gnome/gdk.git
version required: *
```

**Comment by gkoz** [comment]
#25 is supposed to deal with that

**Comment by gkoz** [comment]
@oakes 
That PR has been merged. You'll have to modify your app a bit, like so:
https://github.com/rust-gnome/gtk/commit/54d09b68f2220fb310cae78f88951106c8518122#diff-fb833cc84429770f7f03bc8400e78b57
https://github.com/rust-gnome/gtk/commit/54d09b68f2220fb310cae78f88951106c8518122#diff-6aa93c7f208b0bd3c6ab84ad029a808c

**Comment by oakes** [comment]
Thanks! I have transitioned my project over to the new libraries.
