### ISSUE TITLE
How to draw in-memory images to a window?

### ISSUE THREAD

**Issue by cybergeek94** [rust-gnome/gtk#28]
My application needs to draw in-memory RGB and grayscale images to the screen for display. Piston and Conrod make this easy but I'm looking for a GUI toolkit that is more robust and can produce a native look and feel.

It looks like this might be implemented by creating the `GdkPixBuf` struct and then adding support for creating an `rgtk::gtk::Image` backed by one and getting a mutable reference to it.

**Comment by StephanvanSchaik** [comment]
At the moment, [the implementation of `GtkImage`](https://github.com/rust-gnome/gtk/blob/master/src/widgets/image.rs) is a basic one. To support the creation of a `GtkImage` from a `GdkPixBuf`, [`gtk_image_new_from_pixbuf`](https://developer.gnome.org/gtk3/stable/GtkImage.html#gtk-image-new-from-pixbuf) should be implemented. The `GdkPixBuf` already has been implemented as [`Pixbuf`](https://github.com/rust-gnome/gdk/blob/master/src/widgets/pixbuf.rs).

Once my pull request for 32-bit has been merged. I will pick that up.

In the meanwhile, it should be possible to use a GtkDrawingArea in conjunction with Cairo. See [this example](https://github.com/rust-gnome/gtk/blob/master/examples/src/cairotest.rs). Although, it kind of depends on what you are planning to do exactly.

**Comment by cybergeek94** [comment]
It's for [this project][1]. I want to display images already loaded into memory with [rust-image][2] from Piston, alongside a generated black-and-white image of their hash, as shown in [this article][3].

I'm currently already doing this with Conrod, but I'm having some stuttering issues with loading new images to display, as they have to be copied into OpenGL textures on the main thread because OpenGL contexts cannot be used across threads. I also am having trouble expressing advanced GUI constructs in Conrod's primitive API and I would prefer to have a native look and feel because Conrod's GUI design is pretty homely.

[1]: https://github.com/cybergeek94/img-dup
[2]: https://github.com/PistonDevelopers/image
[3]: http://www.hackerfactor.com/blog/?/archives/432-Looks-Like-It.html

**Comment by StephanvanSchaik** [comment]
Once pull request #32 has been merged, you can create a `GtkImage`, and then upload your in-memory images to the `GdkPixbuf` that has been associated with it using `gdk_pixbuf_get_pixels_with_length` (see ['put_pixel'](https://github.com/rust-gnome/gdk/blob/master/src/widgets/pixbuf.rs#L87) for an example).

**Comment by cybergeek94** [comment]
Excellent work! :+1:

**Comment by cybergeek94** [comment]
@StephanvanSchaik Would it be possible to create a `GdkPixbuf` from image data before creating an `Image` widget, though? Or can `Image` be sent to another thread to be populated before being displayed?

**Comment by StephanvanSchaik** [comment]
In fact, gdk does support that, but the binding does not support it yet. I've added `gdk_pixbuf_new` and `gdk_pixbuf_new_from_subpixbuf` in rust-gnome/gdk#2, but `gdk_pixbuf_new_from_data` might be more interesting for this. However, I am not exactly sure how to handle the `GdkPixbufDestroyNotify` correctly, so I am going to await a response. Nevertheless, these two pull requests should provide a good beginning towards this :).

**Comment by cybergeek94** [comment]
I can copy into the pixel buffer manually, I just need a way to get one first. Can `GdkPixBuf` safely implement `Send`?

**Comment by StephanvanSchaik** [comment]
Considering these [notes on threading](https://developer.gnome.org/gdk3/stable/gdk3-Threads.html), and knowing how GTK+ works internally (I've worked on similar libraries in C before), I don't think transferring `GdkPixbuf` would be safe in all cases. Despite the fact that using the `Send` trait implies transferring ownership between threads. The problem I foresee here is that the GTK+ binding deals with interior mutability, without being explicit about it (i.e. it doesn't use `Rc` and `RefCell`), which means that you could, for instance, grab the `GdkPixbuf` behind a `GtkImage` and transfer it to another thread, which would be problematic. It would however be safe, if you can guarantee that GTK+ is not using the `GdkPixbuf` in question.

In your case, it could be possible to wrap the `GdkPixbuf` in something that can be sent across threads, as you can create a `GdkPixbuf` in your worker thread, where you already have this guarantee that GTK+ itself is not fiddling with it. So it would be safe to create a `GdkPixbuf` and then send it to the main thread, where it could then be used within GTK+. Alternatively, you can also wrap up the pixel data, sent it to the main thread, and then wrap it up in an actual `GtkPixbuf`.

**Comment by GuillaumeGomez** [comment]
The PR has been merged.

**Comment by GuillaumeGomez** [comment]
Is it ok to close ?

**Comment by cybergeek94** [comment]
Yeah, I think we're good here.
