### ISSUE TITLE
Can't build due to usage of removed std::num::FromPrimitive

### ISSUE THREAD

**Issue by matachi** [rust-gnome/gtk#42]
I cloned the examples repo, https://github.com/rust-gnome/examples, and tried to build it with the latest Rust nightly. However, it fails since `gtk-sys` depends on `std::num::FromPrimitive` which has been removed from Rust's API. Here's another project that experienced the same problem: https://github.com/brson/rust-sdl/issues/165

My terminal output:

    $ rustc --version
    rustc 1.1.0-nightly (5fb0259ed 2015-04-26) (built 2015-04-27)
    $ cargo clean
    $ cargo build
      Compiling libc v0.1.6
      Compiling gcc v0.3.4
      Compiling bitflags v0.1.1
      Compiling c_vec v1.0.11
      Compiling pkg-config v0.3.3
      Compiling gtk-sys v0.1.0 (https://github.com/rust-gnome/gtk#0121d69b)
      Compiling gdk-sys v0.1.0 (https://github.com/rust-gnome/gdk#2b1fc225)
      Compiling pango-sys v0.1.0 (https://github.com/rust-gnome/pango#3ce36f5e)
      Compiling glib-sys v0.1.0 (https://github.com/rust-gnome/glib#e8fc0580)
      Compiling cairo-sys v0.1.0 (https://github.com/rust-gnome/cairo#93cb13e5)
      Compiling glib v0.0.1 (https://github.com/rust-gnome/glib#e8fc0580)
      Compiling pango v0.0.1 (https://github.com/rust-gnome/pango#3ce36f5e)
      Compiling cairo v0.0.1 (https://github.com/rust-gnome/cairo#93cb13e5)
      Compiling gdk v0.0.1 (https://github.com/rust-gnome/gdk#2b1fc225)
    /home/matachi/.cargo/git/checkouts/gtk-d0515cff4231591e/master/gtk-sys/src/enums.rs:816:47: 816:60 error: use of undeclared trait name `std::num::FromPrimitive`
    /home/matachi/.cargo/git/checkouts/gtk-d0515cff4231591e/master/gtk-sys/src/enums.rs:816 #[derive(Clone, PartialEq, PartialOrd, Debug, FromPrimitive, Copy)]
                                                                                                                                          ^~~~~~~~~~~~~
    /home/matachi/.cargo/git/checkouts/gtk-d0515cff4231591e/master/gtk-sys/src/enums.rs:816:47: 816:60 note: in expansion of #[derive_FromPrimitive]
    /home/matachi/.cargo/git/checkouts/gtk-d0515cff4231591e/master/gtk-sys/src/enums.rs:816:47: 816:60 note: expansion site
    error: aborting due to previous error
    Build failed, waiting for other jobs to finish...
    Could not compile `gtk-sys`.

    To learn more, run the command again with --verbose.

**Comment by GuillaumeGomez** [comment]
I think that just changed in rust nightly. I'll fix that tonight (or maybe you wanna fix it yourself ? Feel free to open a PR).

**Comment by MaTachi** [comment]
I'm not very experienced with Rust. But applying this change makes it compile:

```diff
diff --git a/gtk-sys/src/enums.rs b/gtk-sys/src/enums.rs
index 3c04636..42aad25 100644
--- a/gtk-sys/src/enums.rs
+++ b/gtk-sys/src/enums.rs
@@ -813,7 +813,7 @@ pub enum License {
 /// Predefined values for use as response ids in gtk_dialog_add_button().
 /// All predefined values are negative, GTK+ leaves positive values for application-defined response ids.
 #[repr(C)]
-#[derive(Clone, PartialEq, PartialOrd, Debug, FromPrimitive, Copy)]
+#[derive(Clone, PartialEq, PartialOrd, Debug, Copy)]
 pub enum ResponseType {
     /// Returned if an action widget has no response id, or if the dialog gets programmatically hidden or destroyed
     None        = -1,
```

However, I not experienced enough to know what side effects this change might have.

**Comment by gkoz** [comment]
We should probably start targeting rust-beta instead of nightly.

**Comment by GuillaumeGomez** [comment]
@gkoz: not for now. When rust 1.0 will be out, we'll create a branch to support nightly.

**Comment by gkoz** [comment]
The 1.0 release is very close. We won't fix everything overnight. Also I'm not sure there's much benefit to tracking nightlies at the moment.

**Comment by GuillaumeGomez** [comment]
It's about to give the possibility, nothing more. The master will be on the release. And try to compile rgtk with the beta. =D

**Comment by gkoz** [comment]
I know it doesn't build on beta today. Two weeks is about the right amount of time to fix everything but we can't do that if we don't decide to start tracking beta.

**Comment by GuillaumeGomez** [comment]
It's not a problem if we're not compiling on the release the first day. I prefer wait and then start the work.

**Comment by gkoz** [comment]
Evidently it's already become an issue for someone and the number of people expecting the project to build on the beta and then the stable channel is going to increase every day now.

**Comment by GuillaumeGomez** [comment]
We _can't_ compile with the beta since it's all buggy. Features aren't working for example.

**Comment by gkoz** [comment]
Whatever hasn't been stabilized will need to be let go or worked around. I feel pretty stupid now for pushing the use of `Unique` that's still unstable, but it is what it is.. ;)

**Comment by GuillaumeGomez** [comment]
You couldn't guess, that's not a problem, we'll change it if it is needed.

**Comment by GuillaumeGomez** [comment]
I suppose this issue can be closed now ?

@gkoz: Unique won't be stabilized before 1.0 release.

**Comment by gkoz** [comment]
@GuillaumeGomez so do we back it out of `c_vec` or eliminate the `c_vec` dependency here? Not bumping `c_vec` to at least `1.1` bites us now because we could've maintained parallel branches with different APIs.

**Comment by GuillaumeGomez** [comment]
I think it's better to update `c_vec`. `gtk` isn't the only project to use it so I'll have to change it a day or another before the 1.0 release.

I'll update it tonight, or maybe you wanna do it ? You implemented the Unique part so as you prefer.

**Comment by gkoz** [comment]
Maybe we still can solve this relatively gracefully: you make another branch and bump one of them to 1.1 now and then we can also release 1.0.12 with `Unique` removed.

**Comment by GuillaumeGomez** [comment]
I think it would be preferrable to just remove `Unique` with version 1.0.12. People who want to keep the `Unique` handling will just stay on the 1.0.11.

**Comment by gkoz** [comment]
That wouldn't let us fix anything else that could need fixing in 1.0.11.
`Unique` will get stabilized sooner or later so it's the Rust 1.0 needs that are temporary but a forward-looking branch doesn't need to break at all. I we make a 1.1 branch now, users that are cool with nightlies will not experience any breakage at all and those targeting Rust 1.0 can stay on `c_vec` 1.0.

**Comment by GuillaumeGomez** [comment]
Okay, I didn't saw it that way. I create the 1.1 branch.

**Comment by gkoz** [comment]
Meh. Turns out neither of `std::thunk` and `FnBox` is stable so we can't make `c_vec` with destructors work with 1.0. We may have to remove this dependency from `gtk` after all...

**Comment by GuillaumeGomez** [comment]
And so the 1.1 branch isn't needed anymore. Why not ? We should give it a try.

**Comment by gkoz** [comment]
This seems to be resolved.

**Comment by GuillaumeGomez** [comment]
Indeed.
