### ISSUE TITLE
gtk macro isn't working normally ?

### ISSUE THREAD

**Issue by GuillaumeGomez** [rust-gnome/gtk#67]
I can't use the function set_activate_on_single_click of TreeView whereas I have a 3.10 installed version. After removing the cfg, it works just fine. Any idea @gkoz ?

**Comment by gkoz** [comment]
What's in your project's `Cargo.toml`?

**Comment by GuillaumeGomez** [comment]
[This](https://github.com/GuillaumeGomez/processus-viewer/blob/master/Cargo.toml). But I guess I forgot everything... Did I ?

**Comment by gkoz** [comment]
This will give you `3.6`. For 3.10 you need to add
```
[features]
default = ["gtk/gtk_3_10"]
```

**Comment by GuillaumeGomez** [comment]
Yes, just like I thought after you asked for Cargo. Isn't there a way to generate automatically the feature ?

**Comment by gkoz** [comment]
It may be possible to find out the version of the installed library but I'm not sure if we can inject that information back into cargo. Also not sure it is worth the trouble.

**Comment by GuillaumeGomez** [comment]
Don't think so but it could be a nice idea to implement. I'll keep that in mind for later.
