### ISSUE TITLE
Submit to crates.io

### ISSUE THREAD

**Issue by GuillaumeGomez** [rust-gnome/gtk#7]
[original](https://github.com/jeremyletang/rgtk/issues/158).

**Comment by gsingh93** [comment]
A lot has happened since the last comment on this thread. Any status update? What needs to be done before this can be put on crates.io?

**Comment by bombless** [comment]
I think they mean that this library will change rapidly these days so they may want to wait for a while before the library become relatively stable.

**Comment by GuillaumeGomez** [comment]
I wait the new signal infrastructure but it will be very soon, don't worry !

**Comment by gsingh93** [comment]
This is done now, right?

**Comment by GuillaumeGomez** [comment]
For a while now. Here's the link : https://crates.io/crates/gtk.
