### ISSUE TITLE
Crash (SIGBUS) when using connect_size_allocate

### ISSUE THREAD

**Issue by jashephe** [rust-gnome/gtk#85]
Attempting to connect to the `size-allocate` signal via `connect_size_allocate` appears to result in an immediate runtime crash with
```
'./target/debug/proof_of_concept' terminated by signal SIGBUS (Misaligned address error)
```

[This gist](https://gist.github.com/jashephe/fadcbf91b632144e6af5) has a simple minimal working example.  Comment out [L24-L26](https://gist.github.com/jashephe/fadcbf91b632144e6af5#file-main-rs-L24-L26) to see the expected behavior.

**Comment by GuillaumeGomez** [comment]
cc @gkoz.

**Comment by gkoz** [comment]
It's because `Rectangle` is not a `struct`, it's a `trait`. I'm surprised you can just throw around `*mut SomeTrait`.
I don't have a fix or a concrete plan yet.
This may be an opportunity to just drop the `GdkRectangle` type and use the proper rectangle type from the `cairo` crate throughout.

**Comment by gkoz** [comment]
@jashephe 
The supposed fix has been merged, can you test with the current `master` branches of the libs?

**Comment by jashephe** [comment]
That appears to fix it on my system — thanks for the quick work!

> I'm surprised you can just throw around `*mut SomeTrait`.

I am too.  Is there a reason why this behavior exists, and would it be worth asking the compiler devs?

**Comment by gkoz** [comment]
If you need this fix on crates.io, please say so, I'm not sure if @GuillaumeGomez plans to push the updates often.

> Is there a reason why this behavior exists, and would it be worth asking the compiler devs?

Let's say I've never heard of a raw fat pointer :) And allowing that or a `&[T]` in an `extern "C" fn` signature seems like a bug to me.

**Comment by jashephe** [comment]
I'm working from local copies, so I don't need an update.  I ran into it when working on adding the GDK-Cairo interaction functions as discussed in __rust-gnome/gdk__:[#20](https://github.com/rust-gnome/gdk/issues/20), anyway.

Do you want to open an issue on __rust-lang/rust__ for it?  Or would it be better to ask in IRC?

**Comment by gkoz** [comment]
I don't have the energy for this right now. If you're going to bring this up with the devs, I'd suggest something more permanent than IRC.

**Comment by jashephe** [comment]
You got it.  If I'm feeling productive, I'll try to parse what's going on and open an issue.  Thanks for the help!

**Comment by GuillaumeGomez** [comment]
@gkoz: I was thinking to update the crates.io every week or something like that (every Saturday seems fine) if there is at least one update (which is totally the case this week).

@jashephe: Thanks if you do it ! =D

**Comment by gkoz** [comment]
I've filed https://github.com/rust-lang/rust/issues/26228 about the lack of warnings on putting fat pointers in FFI definitions.
