### ISSUE TITLE
Build failing with libgtk 3.4.2 on Ubuntu 12.04.5 LTS

### ISSUE THREAD

**Issue by wITTus** [rust-gnome/gtk#92]
Hi, 

on my system the build of this library is failing due to `gtk_glue.c` not compiling:

```
$ LC_ALL=C cargo build --features "gtk_3_4"
...
running: "cc" "-O0" "-c" "-ffunction-sections" "-fdata-sections" "-m64" "-fPIC" "-I" "/usr/include/gtk-3.0" "-I" "/usr/include/pango-1.0" "-I" "/usr/include/gio-unix-2.0/" "-I" "/usr/include/atk-1.0" "-I" "/usr/include/cairo" "-I" "/usr/include/gdk-pixbuf-2.0" "-I" "/usr/include/freetype2" "-I" "/usr/include/glib-2.0" "-I" "/usr/lib/x86_64-linux-gnu/glib-2.0/include" "-I" "/usr/include/pixman-1" "-I" "/usr/include/libpng12" "-DGTK_3_4" "-DGTK_3_6" "/home/foo/.cargo/registry/src/github.com-1ecc6299db9ec823/gtk-sys-0.1.1/src/gtk_glue.c" "-o" "/home/foo/compile/gtk/target/debug/build/gtk-sys-feb460ce2233f27e/out/src/gtk_glue.o"

command did not execute successfully, got: exit code: 1

--- stderr
/home/foo/.cargo/registry/src/github.com-1ecc6299db9ec823/gtk-sys-0.1.1/src/gtk_glue.c:405:1: error: unknown type name 'GtkLevelBar'
```

On my system only GTK 3.4.2 is available. However, as you can see in the output above cargo sets the preprocessor definition `GTK_3_6` anyway.

Cargo & Rust version:

```
$ rustc -V
rustc 1.2.0-dev (aca207a65 2015-05-19) (built 2015-05-19)
$ cargo -V
cargo 0.3.0 (a1778ef 2015-05-19) (built 2015-05-20)
```

It seems as if the `default` value (set to `gtk_3_6`) in `Cargo.toml` is always considered, even when overridden by the `--features` flag.

The following approaches fixed the problem for me.

* Remove the default setting altogether:

```
diff --git a/Cargo.toml b/Cargo.toml
index 7776495..174b575 100644
--- a/Cargo.toml
+++ b/Cargo.toml
@@ -17,7 +17,6 @@ keywords = ["gtk", "gnome", "GUI"]
 name = "gtk"
 
 [features]
-default = ["gtk_3_6"]
 gtk_3_4 = ["gtk-sys/gtk_3_4", "gdk/gdk_3_4"]
 gtk_3_6 = ["gtk-sys/gtk_3_6", "gdk/gdk_3_6", "gtk_3_4"]
 gtk_3_8 = ["gtk-sys/gtk_3_8", "gdk/gdk_3_8", "gtk_3_6"]
```

* Change the default setting to gtk_3_4:

```
diff --git a/Cargo.toml b/Cargo.toml
index 7776495..c08400f 100644
--- a/Cargo.toml
+++ b/Cargo.toml
@@ -17,7 +17,7 @@ keywords = ["gtk", "gnome", "GUI"]
 name = "gtk"
 
 [features]
-default = ["gtk_3_6"]
+default = ["gtk_3_4"]
 gtk_3_4 = ["gtk-sys/gtk_3_4", "gdk/gdk_3_4"]
 gtk_3_6 = ["gtk-sys/gtk_3_6", "gdk/gdk_3_6", "gtk_3_4"]
 gtk_3_8 = ["gtk-sys/gtk_3_8", "gdk/gdk_3_8", "gtk_3_6"]
```

Best Regards,
Sascha

**Comment by GuillaumeGomez** [comment]
Hum... That's weird. @gkoz: what do you think of this ?

**Comment by gkoz** [comment]
Here's how you build for 3.4: https://github.com/rust-gnome/gtk/issues/83#issuecomment-103454481
Changing the default would be a breaking change for those who use 3.6.

**Comment by wITTus** [comment]
Thank you, it works now.

But only for client applications. Not for building the library itself.

Couldn't you add the default value in `build.rs` after checking that no `CARGO_FEATURE_GTK_...`-flag was set at all?

**Comment by gkoz** [comment]
There's `--no-default-features` cargo flag also.

**Comment by wITTus** [comment]
Fair enough. I guess this can be closed then? Building for 3.4 should be documented explicitly maybe. Keep up the good work guys! :+1:

**Comment by GuillaumeGomez** [comment]
@wITTus: Thanks ! And yes, it should be to avoid future potential issues. @gkoz: Can you add the explanation please ?

**Comment by GuillaumeGomez** [comment]
@wITTus: I guess your problem is fixed now. I close it then. Thanks for reporting your issue !
